@startuml
class Sound.SoundManager {
- {static} SoundManager INSTANCE
- float sfxVolume
- float musicVolume
- Clip bgmClip
- <<Create>> SoundManager()
+ {static} SoundManager getInstance()
+ void playBGM(String)
+ void stopBGM()
+ void playSFX(String)
+ void setSfxVolume(float)
+ void setMusicVolume(float)
+ float getSfxVolume()
+ float getMusicVolume()
- void applyVolume(Clip,float)
- float clamp(float)
}


@enduml